version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/javascript"
    target-branch: "main"
    labels:
      - "javascript"
      - "minor dependency updates"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: lockfile-only
    groups:
      npm-production-minor-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-development-minor-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/javascript"
    labels:
      - "javascript"
      - "major dependency updates"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: increase-if-necessary
    groups:
      npm-production-major-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
      npm-development-major-dependencies:
        dependency-type: "development"
        update-types:
          - "major"
