version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "minor version updates"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: increase-if-necessary
    groups:
      npm-production-minor-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-development-minor-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "major version updates"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: increase-if-necessary
    groups:
      npm-production-major-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
      npm-development-major-dependencies:
        dependency-type: "development"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
