name: Combine Dependabot PRs

on:
  schedule:
    - cron: '0 6 * * 1' # At 06:00 (UTC) on Mondays - 01:00 (EST)
  workflow_dispatch: # allows you to manually trigger the workflow

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.2.0
        with:
          labels: combined-pr
          ci_required: 'false'
          ignore_label: "no combine"
